#include <unordered_map>
#include <QDomNodeList>
#include <any>
#include <sstream>
#include <vector>
#include <QDomDocument>
#include <QString>
#include <QFile>
#include <QTextStream>
#include <map>
#include <string>
#include <iostream>
#include <tuple>
#include <type_traits>
#include <utility>
#include <matio.h>
#include <QGlobalStatic>
#include <cstring>
#include <cstdint>
#include <memory>
#include <chrono>
#include <QtConcurrent>
#include <QMutex>
#include <fstream>
#include <variant>
#include <stdexcept>
#include <iterator>
#include <algorithm>
#include <cctype>
#include <regex>
